services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: nasdev
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

  spring-boot-3-example:
     container_name: spring-boot-3-example
     image: nasserbouk/spring-boot-3-example
     environment:
       SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
     ports:
       - "8088:8080"
     networks:
       - db
     depends_on:
       - db
     restart: unless-stopped
     command:
       - --spring.datasource.url=jdbc:postgresql://db:5432/customer


networks:
  db:
    driver: bridge

volumes:
  db: